VictoryFairy/VictoryFairy-backend

src/services/game.service.ts

스코어가 Number(null)로 NaN이 되어버리는 경우가 있습니다.
하지만 문자 중계 정보를 보면 또 제대로 되어 있고, 할 때마다 오류가 나는 경기가 달라집니다.
그래서 그냥 NaN 값이 들어오면 업데이트를 하지 않도록 했습니다!
원인이 무엇인지 알기 전까지는 그냥 이렇게 둘려고 합니다...

점수 업데이트 시 NaN 값을 무시하도록 수정

---

src/services/game.service.ts
src/services/registered-game.service.ts
src/types/registered-game-status.type.ts

등록 경기의 status를 한글에서 영어로 변경
경기 등록 시 경기가 종료되었거나 취소되어있으면 status가 바로 업데이트되도록 변경

🐛 등록 경기의 status 변경 및 생성 시 status 반영

---

src/controllers/registered-game.controller.ts
src/services/registered-game.service.ts

등록 경기 update를 Patch로 바꾸고, 서비스 로직도 이에 맞게 일부 변경 식으로 수정했습니다.

🩹 등록 경기 수정 메소드를 Patch로 변경 및 이에 맞게 서비스 로직 수정

---

src/controllers/cheering-song.controller.ts
src/dtos/cheering-song.dto.ts
src/dtos/cursor-page.dto.ts
src/dtos/game.dto.ts
src/dtos/player.dto.ts
src/services/cheering-song.service.ts
src/services/registered-game.service.ts

경기, 응원가 API가 프론트 뷰에 알맞지 않은 정보를 보내주었던 것을 수정했습니다.
이미 #81 에서 설명했지만, 제네릭이었던 것을 제네릭이 아니게 변경했습니다.

🩹 DTO 프론트 뷰에 맞게 변경

---

src/controllers/cheering-song.controller.ts
src/services/cheering-song.service.ts

유저가 좋아요한 응원가 목록을 무한스크롤 정보와 함께 반환하는 API를 추가했습니다.

✨ 좋아요한 응원가 목록을 무한 스크롤 정보와 함꼐 반환하는 API 추가

---

src/controllers/cheering-song.controller.ts
src/services/cheering-song.service.ts

좋아요한 응원가 엔드 포인트를 타입에 따라 필터링 하도록 변경했습니다.
resolves #87

✨ 좋아요한 응원가 엔드포인트를 타입에 따라 나눔

---

src/seeds/cheering-song.seed.ts
src/services/cheering-song.service.ts

refined-cheering-songs의 json 파일이 import 되는 곳을 만들어서
build 시 dist에 포함될 수 있도록 했습니다.

🐛 dist에 refined-cheering-songs가 포함되지 않는 현상 수정

---

src/dtos/registered-game.dto.ts
src/entities/registered-game.entity.ts
src/services/registered-game.service.ts

직관 경기 등록 시 이미지를 등록하지 않는 경우를 고려하여 이미지 주소 값에 null을 사용할 수 있도록 했습니다.
그에 따라, 업데이트 시의 로직도 조금 수정했습니다.

♻️ 등록 경기의 이미지 주소 값을 nullable 하게 변경

---

src/dtos/registered-game.dto.ts
src/services/game.service.ts
src/services/scheduling.service.ts
src/utils/get-next-month.util.ts

월말에는 다음 달의 경기에 대한 정보가 필요한 바,
경기 데이터를 가져올 때 이번 달과 다음 달의 경기에 대한 정보를 모두 가져오도록 변경했습니다.

✨ 다음 달 경기의 정보도 가져오도록 수정

---

src/dtos/game.dto.ts
src/services/aws-s3.service.ts
src/services/game.service.ts
src/services/registered-game.service.ts
src/services/scheduling.service.ts
src/types/crawling-game.type.ts

경기 상태 업데이트 시의 로직을 수정하여 등록된 경기의 상태가 업데이트가 잘 되지 않는 것을 수정했습니다.
이에 따라 랭킹의 업데이트도 원활하게 될 것입니다.

🐛 경기 상태 업데이트 로직 수정

---

docker-compose.prod.yml
docker-compose.yml
src/services/game.service.ts
src/services/registered-game.service.ts

타임존을 설정하여 로그, 오늘의 경기 부분에서 이에 관련된 오류를 수정했습니다.
경기의 status가 경기 종료이고 **동점이 아닌데도 불구하고 winning_team이 null이거나 불러오지 못하는 오류가 있는 것 같아**
직관 등록 경기의 상태 결정 시 winning_team을 참조하지 않도록 수정했습니다.

타임존 설정 / 등록 경기의 상태 결정 시 winning_team을 참조하지 않도록 핫픽스

---

package-lock.json
package.json
src/dtos/batch-update-game.dto.ts
src/services/game.service.ts

스크래핑한 문자 중계 스코어 값이 number 이면 parseInt하고, 아니라면 null을 반환하도록 변경
그에 따라 스코어 업데이트 로직도 isNaN()을 삭제하여 간소화

🐛 스크래핑한 문자 중계 스코어 값이 number나 null이도록 변경 및 업데이트 로직 변경

---

src/services/game.service.ts

더블 헤더로 변경된 경기의 기존 레코드를 삭제하여 중복을 방지했습니다.
하지만 삭제 후에도 더블 헤더 경기를 업데이트 할 때마다 해당 로직을 실행하도록 하는 문제가 있습니다.
향후 수정이 필요합니다.

🚑 더블 헤더로 변경된 경기의 기존 레코드를 삭제하도록 변경

---

src/services/registered-game.service.ts

등록 경기의 응원 팀 수정 시 등록 경기의 상태 (승패여부) 를 변경합니다.

🩹 등록 경기 응원 팀 수정 시 등록 경기의 상태 변경

---

src/utils/teamid-mapper.ts

현재 팀 이름이 나눔 / 드림인 경기에서 경기id의 팀id 부분이 undefined가 되는 문제가 있습니다.
아마 teamNameToTeamId 에 해당 필드가 없어서 생기는 문제인 것 같은데, 일단 하드 코딩으로 추가 했습니다.
**이 수정은 일단 일시적 해결책으로, 왜 seriesId가 9인 해당 이벤트 경기가 등록되게 되는지에 대한 원인을 파악하지는 못했습니다.**
**또한, 이로인해 team 테이블에 나눔 / 드림에 대한 레코드가 생성되어 응원가의 팀 선택 부분에 나눔 / 드림에 대한 메뉴가 추가되어 있습니다.**

🩹 경기 저장 시 teamId 부분이 undefined가 되는 문제 일시적 해결

---

src/app.module.ts

- Error: DataSource with name "default" has already added.
- Error: DataSource with name "default" has already added. 에러 수정을 위해서 코드 수정했습니다.
- 참고 : https://github.com/Aliheym/typeorm-transactional/issues/53

🐛 :typeorm-transactional bug fix

---

.github/workflows/staging-deploy.yml

- 홈서버에서 도커 이미지 가져올 때 도커 허브 로그인 후 가져오기

👷 : 개발 서버 배포 시 도커허브 인증되도록 수정

---

src/controllers/team.controller.ts
src/services/team.service.ts

/teams가 id가 1-10인 정규 팀만을 반환하도록 변경했습니다.
나눔, 드림의 경우 id가 691,692입니다.

/teams가 정규팀 목록만 반환하도록 수정

---

src/modules/user/user.service.ts

- initialSignUpType 값 생성 시 user없는지 확인하지 않고 local_auth 값을 접근할 때 런타임 에러 발생

🚑 : 이메일 중복확인에서 로직 에러 수정

---

src/core/mail/mail.service.ts

- 이메일 내용에 text도 같은 내용으로 추가 
- 참고 : https://stackoverflow.com/questions/40608635/email-send-through-nodemailer-goes-into-spam-for-gmail

🐛 : spam 처리되는 문제 수정 시도

---

src/modules/game/game.service.ts
src/modules/scheduling/scheduling.service.ts

- 스케줄링 서비스의 경기 종료 및 취소 상태 처리 시 onComplete 콜백 쓰지 않고 바로 로직 처리하는 방식으로 변경
- 크론잡 onComplete 콜백 쓰지 않고 분기 후 후속 로직 처리로 변경

fix/prevent duplicate cron jobs by deleting after stop()
