VictoryFairy/VictoryFairy-backend

- package-lock.json
- package.json
- src/app.module.ts
- src/config/database.config.ts
- src/controllers/game.controller.ts
- src/controllers/parking-info.controller.ts
- src/controllers/registered-game.controller.ts
- src/controllers/stadium.controller.ts
- src/controllers/team.controller.ts
- src/controllers/user.controller.ts
- src/entities/game.entity.ts
- src/entities/parking-info.entity.ts
- src/entities/registered-game.entity.ts
- src/entities/stadium.entity.ts
- src/entities/team.entity.ts
- src/entities/user.entity.ts
- src/modules/game.module.ts
- src/modules/parking-info.module.ts
- src/modules/registered-game.module.ts
- src/modules/stadium.module.ts
- src/modules/team.module.ts
- src/modules/user.module.ts
- src/services/game.service.ts
- src/services/parking-info.service.ts
- src/services/registered-game.service.ts
- src/services/stadium.service.ts
- src/services/team.service.ts
- src/services/user.service.ts
resolves #6 
ERD에 맞추어서 엔티티를 생성하고 모듈, 컨트롤러, 서비스 등의 파일을 생성했습니다.
> ✨ ERD에 맞춰서 엔티티 생성

- .github/workflows/docker-aws-deploy.yml
배포 환경에서 EB에 도커허브 및 EB의 액세스 키와 시크릿 키에 대한 변수는 넘어가지 않도록 했는데, 
이것 때문에 S3의 환경 변수도 넘어가지 않아서 AWS에서 문제가 발생했었습니다.
Resolves #27
> 🚑 EB 액세스 키 이름 바꾸고 적용

- src/controllers/team.controller.ts
- src/dtos/team.dto.ts
- src/services/game.service.ts
- src/services/team.service.ts
> ✨ 팀 관련 API 추가

- src/controllers/registered-game.controller.ts
- src/dtos/registered-game.dto.ts
- src/entities/game.entity.ts
- src/entities/registered-game.entity.ts
- src/entities/stadium.entity.ts
- src/services/registered-game.service.ts
컨트롤러에서 Dto 변환을 수행하도록 수정했습니다.
서비스에서는 엔티티를 반환합니다.
> 컨트롤러에서 Dto 변환 수행하도록 수정

- src/controllers/stadium.controller.ts
- src/controllers/team.controller.ts
- src/dtos/stadium.dto.ts
- src/services/stadium.service.ts
> ✨ 경기장 관련 API 추가

- src/controllers/game.controller.ts
- src/controllers/parking-info.controller.ts
- src/controllers/registered-game.controller.ts
- src/controllers/stadium.controller.ts
- src/controllers/team.controller.ts
- src/dtos/game.dto.ts
- src/dtos/registered-game.dto.ts
- src/entities/game.entity.ts
- src/services/game.service.ts
- src/services/registered-game.service.ts
- src/services/scheduling.service.ts
- src/services/stadium.service.ts
> 경기 관련 API 작성

- src/controllers/parking-info.controller.ts
- src/dtos/parking-info.dto.ts
- src/modules/parking-info.module.ts
- src/seeds/parking-info.seed.ts
- src/services/parking-info.service.ts
- src/services/seeder.service.ts
> 주차장 정보 API 추가

- src/dtos/registered-game.dto.ts
- src/entities/registered-game.entity.ts
- src/filters/typeorm-exception.filter.ts
- src/services/registered-game.service.ts
한 유저가 같은 경기를 중복해서 등록하는 것을 방지 합니다.
resolves #34
> 경기 중복 등록 방지

- src/services/scheduling.service.ts
> 🐛 경기 취소 시 스코어 업데이트 중단 로직 추가

- src/controllers/game.controller.ts
- src/controllers/parking-info.controller.ts
- src/controllers/registered-game.controller.ts
- src/controllers/stadium.controller.ts
- src/controllers/team.controller.ts
- src/dtos/game.dto.ts
- src/dtos/parking-info.dto.ts
- src/dtos/registered-game.dto.ts
- src/dtos/stadium.dto.ts
- src/dtos/team.dto.ts
- src/dtos/user-dto.ts
- src/modules/game.module.ts
- src/modules/parking-info.module.ts
- src/modules/registered-game.module.ts
- src/modules/scheduling.module.ts
- src/modules/stadium.module.ts
- src/modules/team.module.ts
- src/services/stadium.service.ts
- src/services/user.service.ts
> API 문서 상세화

- src/config/database.config.ts
- src/services/seeder.service.ts
- src/services/user.service.ts
- db drop schema 옵션 제외
- 유저 목 데이터 초기 셋팅 코드 제외
> [Chore] drop schema 빼기

- src/dtos/registered-game.dto.ts
- src/entities/registered-game.entity.ts
> 🐛 직관 경기 등록 시 오류 수정

- src/auth/auth.controller.ts
- src/auth/auth.service.ts
- 로그인할 때 팀아이디 이름 반환
- 리프레쉬 토큰 체크 엔드포인트 추가
> [feature] 로그인 시 팀 아이디 이름 조회 및 리프레쉬 토큰 체크 엔드포인트 추가

- src/services/parking-info.service.ts
주차장 정보 API에서 경기장 정보가 빠진 것을 수정했습니다.
> 🐛 주차장 정보 API에서 경기장 정보가 빠진 것 수정

- src/services/stadium.service.ts
> 🩹 등록되어 있지 않은 경기장 필터링

- src/controllers/aws-s3.controller.ts
- src/dtos/aws-s3.dto.ts
- src/services/aws-s3.service.ts
> ✨ 직관 경기 이미지 등록 및 이미지 삭제 엔드포인트 추가

- src/controllers/cheering-song.controller.ts
- src/controllers/parking-info.controller.ts
- src/controllers/registered-game.controller.ts
- src/controllers/stadium.controller.ts
- src/controllers/team.controller.ts
> 📝 API 문서에 예시 보강

- src/controllers/cheering-song.controller.ts
- src/dtos/cheering-song.dto.ts
- src/dtos/cursor-page.dto.ts
- src/dtos/registered-game.dto.ts
- src/entities/cheering-song.entity.ts
- src/entities/like-cheering-song.entity.ts
- src/entities/player.entity.ts
- src/services/cheering-song.service.ts
- src/services/game.service.ts
- src/services/registered-game.service.ts
> 사용하지 않는 import 삭제

- src/controllers/aws-s3.controller.ts
그냥 복사해가지고 생긴 오타 수정
resolves #89
> ✏️ 직관 경기 이미지 등록 API 반환 값 구조 변경

- src/controllers/user.controller.ts
- src/services/user.service.ts
> [Feature] 비밀번호 확인 엔드포인트 추가

- src/entities/rank.entity.ts
- src/services/rank.service.ts
-  Rank 엔티티 제약조건 추가
-  Rank 엔티티 저장/업데이트 방식 변경
> [Refator] : Rank 엔티티 제약조건 추가, 저장 방식 변경

- .github/workflows/docker-aws-deploy.yml
> 💚 EB 버전 레이블 변경

- src/seeds/convert-invalid-url.ts
- src/services/game.service.ts
- src/services/registered-game.service.ts
등록된 지관 경기의 응답 값에 누락되어 있던 정보 추가
> 🐛 relations를 수정하여 등록 게임의 응답 값에 누락되어 있던 정보 추가

- .vscode/launch.json
- src/controllers/rank.controller.ts
- src/dtos/rank.dto.ts
- src/dtos/user.dto.ts
- src/services/rank.service.ts
- ranking api 변경
- rankings/list -> rankings : 전체 리스트 반환
- rankings -> rankings/top : 상위 3명
- rankings -> rankings/nearby : 해당 유저와 근처 유저 2명 반환
- 쿼리로 team 선택은 동일
- users/me 점수 포함해서 반환
> [feature]  rank api 변경 / user api 응답값 변경

- .github/workflows/docker-aws-deploy.yml
- src/services/game.service.ts
> 버전 라벨 수정 및 relations 겨는 방법 변경

- src/controllers/registered-game.controller.ts
- src/decorator/queryrunner-manager.decorator.ts
- src/dtos/rank.dto.ts
- src/entities/rank.entity.ts
- src/interceptor/transaction.interceptor.ts
- src/modules/registered-game.module.ts
- src/services/rank.service.ts
- src/services/registered-game.service.ts
- 과거 경기 직관 등록할 때 rank 테이블 저장과 같이 처리하기 위해 트랜잭션 적용.
> [Feature] 과거 경기 직관 등록 트랜잭션 적용

- src/controllers/cheering-song.controller.ts
- src/dtos/cheering-song.dto.ts
- src/dtos/game.dto.ts
- src/dtos/registered-game.dto.ts
- src/dtos/stadium.dto.ts
일부 DTO의 키를 스네이크 케이스에서 카멜 케이스로 변경하였습니다.
> 일부 DTO의 키를 스네이크 케이스에서 카멜 케이스로 변경

- src/dtos/stadium.dto.ts
경기장 DTO를 변경하여 경기장 API에서 fullName이 표시되도록 변경했습니다.
> 🐛 경기장 DTO 변경하여 fullName 포함하도록 수정

- src/controllers/rank.controller.ts
- src/controllers/user.controller.ts
- src/dtos/rank.dto.ts
- src/dtos/user.dto.ts
- src/services/rank.service.ts
-  랭킹 반환 값 404 에러 대신에 빈배열로 반환
- 랭킹 컨트롤러 스웨거 리팩토링
- 유저 컨트롤러 스웨거 리팩토링
> [Fix] 랭킹 반환 없는 경우 빈배열로 반환 / [Refactor] : 유저, 랭킹 컨트롤러 스웨거 리펙토링

- .github/workflows/docker-aws-deploy.yml
> 💚 변경된 AWS 설정 반영

- docker-compose.local.yml
- docker-compose.prod.yml
- docker-compose.yml
> [Chore]: redis max memory 100mb로 수정

- src/auth/auth.controller.ts
> ✨ : cookie secure 옵션 추가

- src/auth/guard/access-token.guard.ts
- src/const/event.const.ts
- src/controllers/rank.controller.ts
- src/controllers/user.controller.ts
- src/dtos/rank.dto.ts
- src/interceptor/transaction.interceptor.ts
- src/services/rank.service.ts
- src/services/scheduling.service.ts
- src/services/user.service.ts
- rank controller dto 적용 안되어서 profile_image로 반환하는 문제 수정
- 회원가입하면 바로 전체와 응원팀 랭킹에 반영하기
- 당일 직관 경기가 업데이트되면 랭킹도 같이 업데이트 되도록 변경
- 동점자 처리 로직 추가
> [Fix, Refactor] rank dto, response data, tie-breaker

- src/interceptor/api-logger.interceptor.ts
- src/interceptor/transaction.interceptor.ts
- src/main.ts
- src/services/rank.service.ts
- src/services/user.service.ts
- api에 대한 글로벌 로깅  인터셉터 추가
- 점수 소숫점 나오는 오류 수정
> [Feature]api logger & [Fix] 점수 소숫점 

- src/config/nodemailer.config.ts
- src/controllers/aws-s3.controller.ts
- 이미지 업로드 용량 제한 6mb 수정
- nodemailer 배포환경에 맞게 설정 수정
> [Config]mailer 설정, img 용량 설정

- src/modules/aws-s3.module.ts
- src/modules/registered-game.module.ts
- src/services/aws-s3.service.ts
- src/services/registered-game.service.ts
이미지 삭제 시 그 결과인 DeleteObjectCommandOutput를 그대로 로깅합니다.
> 이미지 삭제 시 그 결과를 로깅

- src/modules/aws-s3.module.ts
- src/modules/registered-game.module.ts
- src/services/registered-game.service.ts
등록 경기의 이미지 변경/삭제 시 S3의 이미지를 삭제합니다.
> ✨ 등록 경기의 이미지 변경/삭제 시 S3의 이미지 삭제

- src/modules/user.module.ts
- src/services/user.service.ts
> [FIx] 사용하지 않는 프로필 이미지 삭제

- src/services/game.service.ts
> 🐛 innerText가 null 일때 발생하는 오류 수정

- src/services/game.service.ts
> 🐛 StatusElement에도 null 체크

- src/controllers/aws-s3.controller.ts
- src/services/aws-s3.service.ts
> 🔊 이미지 업로드 로그 추가 및 이미지 삭제 엔드포인트 제거

- src/services/aws-s3.service.ts
> 🔊 이미지 관련 로그 수정

- src/services/user.service.ts
> 🚑 : profile delete 문제 해결

- src/services/rank.service.ts
> [Fix] : 점수 증감 10점으로 변경

- src/controllers/game.controller.ts
- src/dtos/batch-update-game.dto.ts
- src/services/game.service.ts
- src/services/rank.service.ts
- src/services/scheduling.service.ts
경기 업데이트 스케쥴러 시간 변경
스케쥴러 종료 로직을 변경하고, onComplete 콜백 함수를 이용하여 경기 status 업데이트에 누락이 없도록 수정
> 경기 업데이트 스케쥴러 시간 및 로직 조금 변경

- src/seeds/game-months.seed.ts
- src/services/game.service.ts
- src/services/scheduling.service.ts
- src/services/seeder.service.ts
> 더블 헤더 기능 및 2023, 2024년에 대한 경기 시드 추가 및 최대 병렬 처리 수 설정

- src/controllers/user.controller.ts
- src/entities/like-cheering-song.entity.ts
- src/modules/user.module.ts
- src/services/user.service.ts
> [Fix]: 유저 탈퇴 시 랭킹에도 반영하도록 수정

- src/interceptor/api-logger.interceptor.ts
> [Refactor]: 헬스체킹은 로깅 인터셉터에서 무시하도록 변경

- src/services/registered-game.service.ts
부등호 방향이 이상해서 홈 팀이 이겼을 때에도 Tie라고 기록했던것을 수정했습니다.
> ✏️ defineStatus의 부등호 방향 정상화

- src/controllers/registered-game.controller.ts
- src/services/rank.service.ts
- src/services/registered-game.service.ts
- 직관 경기 삭제 시 랭킹 테이블 및 랭킹 점수 반영하도록 수정
> [Fix] : 직관 경기 삭제 시 랭킹 테이블 및 랭킹 점수 반영하도록 수정

- src/services/aws-s3.service.ts
- null 값으로 직관 경기가 등록된 경우 삭제 시 s3에 삭제 요청 안하는 방법으로 수정
> [Refactor] : url이 아닌 경우에는 s3에 삭제 요청 안하기

- README.md
> [Doc] : update readme

- src/services/game.service.ts
문자 중계 데이터에서 점수만 들어오고 상태가 null일 때가 있습니다.
따라서 그러한 경우에는 상태만을 업데이트하지 않도록 합니다.
> 🐛 문자 중계 데이터에서 상태가 null로 들어올 때의 예외 처리

- src/services/registered-game.service.ts
한 달 간 리뷰를 반환하는 서비스에서,
리뷰를 경기의 시작일 기준으로 최신순으로 정렬하도록 수정했습니다.
**4시 이후 MERGE!!!**
> ♻️ 한달 간 리뷰를 경기 시작일 기준, 최신순으로 정렬

- src/services/scheduling.service.ts
/^batchUpdate.&/ 정규식이 batchUpdateGames도 포함하는 것 때문에 크론잡이 처음 실행 후에는 실행되지 않는 문제를 해결하였습니다.
> 🐛 앱 실행 시batchUpdateGames 크론잡을 삭제해버리는 것 수정

- src/entities/cheering-song.entity.ts
- src/entities/like-cheering-song.entity.ts
- src/entities/user.entity.ts
유저 삭제 시 My 응원가 cascade 삭제를 추가했습니다.
> 🐛 유저 삭제 시 My 응원가 cascade 삭제

- src/services/game.service.ts
upsert 조건이 date, time, stadium으로 되어 있어 경기 시간이 변경되었을 경우 id에 대한 고유키 제약조건을 위배했습니다.
upsert 조건을 id로 바꾸어 해결합니다.
> 🐛 경기 시간이 변경되었을 경우 고유키 제약조건을 위반하는 것 수정

- src/entities/user.entity.ts
- src/services/registered-game.service.ts
- 당일 경기 종료 후 랭킹 레디스 캐싱 하도록 수정
- 유저 엔티티 불필요한 설정 제거
> [Fix] 레디스 캐싱

- src/services/game.service.ts
점수 스크래핑 시 early return 조건에 있던 오타인 ,를 ||로 변경했습니다.
> 점수 스크래핑 시 로직의 오타 수정

- package-lock.json
- package.json
- src/services/game.service.ts
- src/utils/is-number.util.ts
- tsconfig.json
is-number 라이브러리를 지우고, 직접 구현해서 대체했습니다.
> ➖ is-number 지우고 직접 작성

- docker-compose.prod.yml
- docker-compose.yml
- 도커 컴포즈 파일에 스웨거 로그인 관련 환경변수 추가 했습니다.
> 🚑 : docker compose 파일에 빠진 환경 변수 추가

- src/config/nodemailer.config.ts
- src/interceptor/api-logger.interceptor.ts
- nodemailer의 응답속도 개선
- 첫 메일 전송은 smtp서버와 첫 연결 때문에 속도가 느립니다.
- 로그 메세지에서 응답속도 부분은 노란색으로 나오도록 수정했습니다.
개선 전
개선 후
> 인증 메일 응답속도 개선

- src/interceptor/api-logger.interceptor.ts
- src/services/game.service.ts
- 실시간 게임 업데이트 에러 간단한 사항이여서 그냥 제가 수정했습니다.
- 수정하는 김에 로그 응답속도 제외한 나머지는 예전과 같은 색상으로 나오도록 수정했습니다.
> 실시간 게임 업데이트 에러 수정

- src/services/user.service.ts
> fix : 코드 위치 틀린 부분 수정

- src/services/game.service.ts
> 👔 : 포스트시즌 경기도 크롤링 할 도록 업데이트

- .env-example
- docker-compose.prod.yml
- docker-compose.yml
- src/services/scheduling.service.ts
문자 중계의 seriesId를 환경변수에서 받아오도록 변경했습니다.
> 🩹 문자 중계의 seriesId를 .env에서 받아오도록 변경

- src/services/mail.service.ts
- 인증코드 html 템플릿 수정입니다.
- 네이버 메일에서 인증 코드 받는 경우 Text만 받아지는 문제가 있어서 html 스타일 방법을 수정했습니다.
> fix/auth-code-html-template

- .github/workflows/docker-aws-deploy.yml
- .platform/nginx/conf.d/block-unnecessary-url.conf
- Nginx 설정 파일에 봇 스캐닝을 차단하고 특정 URL 요청을 차단하는 규칙을 추가했습니다.
- 특정 파일 확장자와 URL 경로에 대한 접근을 제한하여 보안을 강화했습니다.
> nginx 특정 url 차단 설정 추가

- src/const/event.const.ts
- src/const/redis.const.ts
- src/services/redis-caching.service.ts
- enum 대신 as const 방식으로 변경했습니다.
- 참고 : https://engineering.linecorp.com/ko/blog/typescript-enum-tree-shaking
> ♻️ : enum 대신 as const 방식으로 변경

- src/services/rank.service.ts
- src/services/redis-connection.service.ts
- src/services/user.service.ts
- src/test/unit/user.servcie.spec.ts
- src/utils/game-crawling.util.ts
- 랭킹 점수 누적연도 데이터 기반으로 계산하도록 수정
- 기본 프로필 이미지에서 다른 프로필 이미지로 변경 시 기본 프로필 이미지 삭제되는 문제 수정
- 크롤링할 때 팀 없는 경우 저장할 때 upsert로 저장하는 방식으로 변경
> Fix/Ranking Calc & Profile Img

- .github/workflows/docker-only-deploy.yml
- .github/workflows/staging-deploy.yml
- docker-compose.staging.yml
- 배포에 필요한 docker-compose.staging.yml 추가
- dev 브랜치 빌드 및 테스트에서 제외
- dev 브랜치에 푸쉬된 경우만 개발 서버 배포
> 🔧 : 개발 서버 깃허브 액션 추가

- src/auth/auth.controller.ts
- src/controllers/user.controller.ts
- src/entities/local-auth.entity.ts
- src/entities/social-auth.entity.ts
- src/migration/files/1740209603509-add-feature-social-loign.ts
- 로그인 시 리프레쉬 토큰 생성 분기 추가
- 회원 탈퇴 시 쿠키 삭제되지 않는 문제 해결
- social_auth, local_auth 테이블 생성/수정 년월일 컬럼 추가
> Fix/social auth bug  & Add/date column

- .github/workflows/docker-aws-deploy.yml
> 🐛 : 애플 환경변수 넣어주도록 깃허브 액션 수정

- .github/workflows/docker-aws-deploy.yml
- apple-private-key github action
> 🚑 : apple-private-key github action

- .github/workflows/docker-aws-deploy.yml
- eb 기존 환경에서 새로운 환경 변경으로 깃허브 액션 파일 수정
> 🔧 : change eb env name

- .github/workflows/docker-aws-deploy.yml
- src/auth/guard/social-auth.guard.ts
- src/auth/strategies/apple.strategy.ts
- apple secret key를 aws eb에 전달가능하도록 수정
> 🐛 : aws apple-private-key 전달되도록 수정

- src/services/rank.service.ts
> 🐛 : top3 엔드포인트 데이터에 랭킹 누락되는 문제 수정

- src/interceptor/api-logger.interceptor.ts
- 배포 서버와 스테이징 서버와 동기화
- eb 헬스 체크 로깅 안하도록 수정
> 🔊 : eb 헬스 체크 로깅 안하도록 수정

- src/modules/registered-game/registered-game.service.ts
- 직관 등록 된 기록 중 상태가 null을 가져오지 않고 전부 가져오는 문제 수정
> fix : null → IsNull()로 수정하여 정확한 필터링 적용

- package-lock.json
- package.json
- src/app.module.ts
- src/app.service.ts
- src/common/guard/cutstom-throttler.guard.ts
- src/core/aws-s3/aws-s3.controller.ts
- src/core/config/nodemailer.config.ts
- src/core/mail/mail.module.ts
- src/core/mail/mail.service.ts
- src/core/redis/redis-throttler-storage.service.ts
- src/core/redis/redis.module.ts
- src/core/seeder/seeder.service.ts
- src/modules/auth/auth.controller.ts
- src/modules/game/game.service.ts
- src/modules/registered-game/registered-game.service.ts
- src/modules/scheduling/scheduling.service.ts
- src/modules/scheduling/type/schedule-job-name.type.ts
- 실제 서비스에서 AWS SES 사용
- 글로벌 쓰로틀러 사용
- 스케줄러잡이 두 번 실행되는 문제 수정
- 스케줄러 서비스 리팩토링
- typeorm  쿼리 시 null로 필터링 안되는 문제 수정
> feature/ses-mailer-throttler& fix/img-size-cronjob

- src/core/config/nodemailer.config.ts
> fix/ ses region problem

- src/core/config/nodemailer.config.ts
- AWS SES 자격 증명 환경 변수가 누락된 경우 오류 발생 처리 추가
- SESClient로 변경
> fix : AWS SES 자격 증명 확인 및 SESClient로 변경

- src/tools/seeds/data/cheering-song-converter.ts
-  응원가 팀명 변경 및 업데이트 - 삼성, SSG, NC, 롯데, LG, KT, 키움, KIA, 한화, 두산 팀명 수정
> fix : 응원가 팀명 변경 및 업데이트 - 삼성, SSG, NC, 롯데, LG, KT, 키움, KIA, 한화, 두산 팀명 수정

- src/modules/account/account.service.ts
- src/modules/scheduling/game-crawling.util.ts
- src/modules/user/user.service.ts
- 스테이징서버 적용
- loginSocialUser에서 try-catch문 제거해서 호출한 메소드의 에러가 제대로 응답에 하도록 수정
- 외부 api 요청이 실패 시 재요청 로직 및 에러로 인해 서버 멈춤 방지
- userService isExistEmail의 리턴 타입 명시
> ♻️ : 에러처리 수정

- src/modules/stadium/dto/stadium.dto.ts
- 스타디움 리턴 시 대전(신) -> 대전 으로 응답하도록 dto 수정
> [stagging]chore/stadium-name-return

- src/modules/scheduling/crawling-game.type.ts
- src/tools/seeds/data/stadium.seed.ts
> [stagging]chore/stadium name return

- src/modules/scheduling/crawling-game.type.ts
- src/modules/stadium/dto/stadium.dto.ts
- src/tools/seeds/data/stadium.seed.ts
- 신구장 시드 데이터 추가 및 스타디움 타입 추가
- stadium dto 수정
> [Deploy]chore/stadium-name

- package-lock.json
- package.json
- src/core/aws-s3/aws-s3.controller.ts
- src/core/aws-s3/aws-s3.service.ts
- src/core/aws-s3/const/s3.const.ts
- src/core/aws-s3/dto/s3.dto.ts
- 스테이징 서버 적용
- pre-signed-url 엔드포인트 구현
> [stagging]Feature/s3 presigned url

- src/modules/registered-game/dto/internal/save-registered-game.dto.ts
- src/modules/registered-game/registered-game.service.ts
- registered-game img dto에서 누락 문제 수정
> [Deploy]fix/registered-game-img

- docker-compose.e2e.yml
- src/common/utils/getGameType.ts
- src/modules/game/dto/game.dto.ts
- src/modules/game/game.controller.ts
- src/modules/scheduling/game-crawling.util.ts
- test/app.e2e-spec.ts
- test/mock/data/correct-game-example.ts
- test/mock/data/mock-games.ts
- 더블헤더 관련 gameType 응답값에 추가
- 승리팀 없는 경우 null로 처리하도록 수정
> [Deploy]Feature/handle double header

- src/modules/game/dto/batch-update-game.dto.ts
- src/modules/game/game.service.ts
- src/modules/scheduling/scheduling.service.ts
- test/utils/test-game-seeder.ts
- 외부 api 호출 시 실패에 대한 에러 핸들링 추가
- rxjs -> axios  + promise.allSettled로 변경
> [Deploy]Fix/handle external api erorr

- src/app.module.ts
- src/common/filters/global-exception.filter.ts
- src/core/aws-s3/aws-s3.module.ts
- src/core/aws-s3/aws-s3.service.ts
- src/core/config/database.config.ts
- src/core/config/dotenv.interface.ts
- src/core/config/nodemailer.config.ts
- src/core/config/redis.config.ts
- src/core/config/s3.config.ts
- src/core/mail/mail.module.ts
- src/core/mail/mail.service.ts
- src/core/slack/slack.service.ts
- src/main.ts
- src/modules/auth/auth.controller.ts
- src/modules/auth/auth.service.ts
- src/modules/auth/strategies/apple.strategy.ts
- src/modules/auth/strategies/base-oauth.strategy.ts
- src/modules/auth/strategies/google.strategy.ts
- src/modules/auth/strategies/jwt.strategy.ts
- src/modules/auth/strategies/kakao.strategy.ts
- src/modules/scheduling/report.schedule.service.ts
- src/modules/scheduling/scheduling.service.ts
- src/modules/user/user.controller.ts
- IDotenv 인터페이스 추가 및 ConfigService에서의 제네릭 타입 사용
> [Stagging]refactor/dotenv-inerface 

- src/core/aws-s3/aws-s3.controller.ts
- src/core/aws-s3/aws-s3.service.ts
- presigned로 대체됨에 따라 파일 직접 업로딩 엔드포인트 제거
> [Stagging]Refactor/delete-img-upload-endpoin

- src/modules/game/dto/response/res-game-daily.dto.ts
- src/modules/game/game.controller.ts
- src/modules/game/game.module.ts
- src/modules/game/game.service.ts
- src/modules/game/util/gamel-list-group-by-team.util.ts
- src/modules/registered-game/registered-game.module.ts
- src/modules/registered-game/registered-game.service.ts
- test/app.e2e-spec.ts
- test/mock/data/correct-game-example.ts
- games/daily 요구사항으로 응답 데이터 변경
- games/today 엔드포인트 추가
- 추후 리팩토링 필수
> [Stagging]feature/handle-ouble-header

- src/common/utils/calculateRankScore.util.ts
- src/modules/rank/dto/internal/aggregate-rank.dto.ts
- src/modules/rank/rank.service.ts
- src/modules/rank/repository/rank.repository.interface.ts
- src/modules/rank/repository/rank.repository.ts
- src/modules/user/dto/response/res-user-me.dto.ts
- src/modules/user/user.controller.ts
- Promise.all로 3개 메소드를 병렬처리했지만 2개의 메소드는 하나의 쿼리로 처리 가능하므로  집계 쿼리 작성 리팩토링
> [Stagging]Refactor/userme

- src/common/utils/calculateRankScore.util.ts
- src/modules/rank/dto/internal/aggregate-rank.dto.ts
- src/modules/rank/rank.service.ts
- src/modules/rank/repository/rank.repository.interface.ts
- src/modules/rank/repository/rank.repository.ts
- src/modules/user/dto/response/res-user-me.dto.ts
- src/modules/user/user.controller.ts
- 유저 랭크 통계 가져올 때 쿼리빌더로 집계해서 가져기 + 쿼리빌더 이용해서 커넥션 수 줄이면서 한번에 데이터 받아오도록 수정
> [Deploy]Refactor/userme

- src/core/aws-s3/aws-s3.controller.ts
- src/core/aws-s3/aws-s3.service.ts
> [Stagging]Fix/presigned-url-length

- src/core/aws-s3/aws-s3.controller.ts
- src/core/aws-s3/aws-s3.service.ts
- 이미지 업로딩 시 파일 사이즈 변조 방지 위한 content-length 추가
> [Deploy]Fix/presigned-url-length
